const colors = {
  light: {
    text: "#0e1b2e",
    tint: "#2563eb",
    background: "#f4f7fb",
    foreground: "#0e1b2e",
    card: "#ffffff",
    cardForeground: "#0e1b2e",
    primary: "#2563eb",
    primaryForeground: "#ffffff",
    secondary: "#eef2f8",
    secondaryForeground: "#0e1b2e",
    muted: "#eef2f8",
    mutedForeground: "#6c7a8d",
    accent: "#eff4ff",
    accentForeground: "#2563eb",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#dce4ef",
    input: "#dce4ef",
    dark: "#1a1d2e",
  },
  dark: {
    text: "#f4f7fb",
    tint: "#60a5fa",
    background: "#0e1b2e",
    foreground: "#f4f7fb",
    card: "#1a2640",
    cardForeground: "#f4f7fb",
    primary: "#3b82f6",
    primaryForeground: "#ffffff",
    secondary: "#1e2d42",
    secondaryForeground: "#f4f7fb",
    muted: "#1e2d42",
    mutedForeground: "#8da3ba",
    accent: "#1e3a5f",
    accentForeground: "#60a5fa",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#2a3d58",
    input: "#2a3d58",
    dark: "#0e1b2e",
  },
  radius: 12,
};

export default colors;
