import { Router, type IRouter } from "express";
import aiRouter from "./ai";
import healthRouter from "./health";
import authRouter from "./auth";
import companiesRouter from "./companies";
import usersRouter from "./users";
import counterpartiesRouter from "./counterparties";
import propertiesRouter from "./properties";
import contractsRouter from "./contracts";
import documentsRouter from "./documents";
import importRouter from "./import";
import rentalRouter from "./rental";
import dashboardRouter from "./dashboard";
import activityRouter from "./activity";
import reportsRouter from "./reports";
import modulesRouter from "./modules";
import investorsRouter from "./investors";
import constructionRouter from "./construction";
import constructionTasksWorkRouter from "./construction-tasks-work";
import constructionFinanceRouter from "./construction-finance";
import constructionBudgetRouter from "./construction-budget";
import constructionReportsRouter from "./construction-reports";
import notificationsRouter from "./notifications";
import notificationsApiRouter from "./notifications-api";
import categoriesRouter from "./categories";
import portalRouter from "./portal";
import portalMarketplaceSupplierRouter from "./portal-marketplace-supplier";
import adminRouter from "./admin";
import legalEntitiesRouter from "./legal-entities";
import bankAccountsRouter from "./bank-accounts";
import rolesRouter from "./roles";
import warehouseRouter from "./warehouse";
import warehouseTransfersRouter from "./warehouse-transfers";
import crmRouter from "./crm";
import platformAdminRouter from "./platform-admin";
import platformAdminMarketplaceRouter from "./platform-admin-marketplace";
import marketplaceRouter from "./marketplace";
import contractDocxRouter from "./contract-docx";
import financeReconciliationRouter from "./finance-reconciliation";
import payrollRouter from "./payroll";
import supplyRouter from "./supply";
import catalogRouter from "./catalog";
import tableViewsRouter from "./table-views";
import contractTerminationsRouter from "./contract-terminations";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(platformAdminMarketplaceRouter);
router.use(platformAdminRouter);
router.use(companiesRouter);
router.use(usersRouter);
router.use(counterpartiesRouter);
router.use(propertiesRouter);
router.use(contractsRouter);
router.use(documentsRouter);
router.use(importRouter);
router.use(rentalRouter);
router.use(dashboardRouter);
router.use(activityRouter);
router.use(reportsRouter);
router.use(modulesRouter);
router.use("/rental", investorsRouter);
router.use("/construction", constructionRouter);
router.use("/construction", constructionTasksWorkRouter);
router.use("/construction", constructionFinanceRouter);
router.use(contractDocxRouter);
router.use("/construction", constructionBudgetRouter);
router.use("/construction", constructionReportsRouter);
router.use("/construction", payrollRouter);
router.use("/finance-reconciliation", financeReconciliationRouter);
router.use(supplyRouter);
router.use(catalogRouter);
router.use(tableViewsRouter);
router.use(contractTerminationsRouter);
router.use(notificationsRouter);
router.use(notificationsApiRouter);
router.use(categoriesRouter);
router.use(portalRouter);
router.use(portalMarketplaceSupplierRouter);
router.use(adminRouter);
router.use(legalEntitiesRouter);
router.use(bankAccountsRouter);
router.use(rolesRouter);
router.use(warehouseRouter);
router.use(warehouseTransfersRouter);
router.use(crmRouter);
router.use(marketplaceRouter);
router.use(aiRouter);

// NBKR exchange rates proxy
router.get("/nbkr/rates", async (req, res): Promise<void> => {
  const { fetchNbkrRatesForDate } = await import("../lib/nbkr");
  const requestedDate =
    typeof req.query.date === "string" ? req.query.date.slice(0, 10) : undefined;
  const payload = await fetchNbkrRatesForDate(requestedDate);
  res.json(payload);
});

export default router;
